### ISSUE TITLE
Could You Please share the Industrial Control System (ICS) Cyber Attack Datasets with Me?

### ISSUE THREAD

**Issue by professor-who** [AlexLeoTW/ICS_attack_DB_analysis#1]

**Comment by AlexLeoTW** [comment]
The site is still up, so... I guess this is what you are looking for?

https://sites.google.com/a/uah.edu/tommy-morris-uah/ics-data-sets

**Comment by professor-who** [comment]
Thank you！But the link is not working/(ㄒoㄒ)/~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AlexLeoTW/ICS_attack_DB_analysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月30日(星期五) 晚上7:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AlexLeoTW/ICS_attack_DB_analysis] Could You Please share the Industrial Control System (ICS) Cyber Attack Datasets with Me? (#1)





 
The site is still up, so... I guess this is what you are looking for?
 
https://sites.google.com/a/uah.edu/tommy-morris-uah/ics-data-sets

**Comment by AlexLeoTW** [comment]
I just checked the download link in the site mentioned above. It's working just fine for me...
Do you have access to Dropbox, I think I might have a copy on it.

Ps. Assuming your internet access is restricted, you might want to change ISP or bypass the limitation with some "tools".

**Comment by professor-who** [comment]
Thanks，I found there is something wrong with my Internet access and I get this datasets successfully now.
